#Paths of controller
controller:
  base-path: api/attendance/
  api-attendance-employees: employees
  api-attendance-employee: employee
  api-attendance-employee-Id: employee/{employeeId}

#Valid headers apis
headers:
  id-user: x-id-usuario

#Swagger Config
spring:
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher